# Generated by Django 5.0.4 on 2024-04-29 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sol_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaofuncionarios',
            old_name='role',
            new_name='funcao',
        ),
    ]
