# Generated by Django 5.0.4 on 2024-04-29 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0002_tipodoc'),
        ('sol_app', '0003_remove_solicitacaofuncionarios_nome_equipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_responsavel', to='cadastro_app.funcionarios'),
        ),
    ]
