# Generated by Django 5.0.4 on 2024-04-29 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0002_tipodoc'),
        ('sol_app', '0004_alter_solicitacao_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='contato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario_contato', to='cadastro_app.funcionarios'),
        ),
    ]
