# Generated by Django 5.0.4 on 2024-04-29 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_app', '0002_tipodoc'),
        ('sol_app', '0005_alter_solicitacao_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaofuncionarios',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_app.funcionarios'),
        ),
        migrations.AlterField(
            model_name='solicitacaofuncionarios',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sol_app.solicitacao'),
        ),
    ]
