# Generated by Django 5.0.4 on 2024-05-06 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol_app', '0011_alter_solicitacao_contato_alter_solicitacao_regiao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='created_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='created_solicitacao_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='updated_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='updated_solicitacao_set', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
