# Generated by Django 5.0.4 on 2024-05-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sol_app', '0013_remove_solicitacao_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('AB', 'Aberta'), ('EA', 'Em andamento'), ('FI', 'Finalizada'), ('CA', 'Cancelada')], default='AB', max_length=2),
        ),
    ]
