# Generated by Django 5.0.4 on 2024-04-29 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_app', '0002_tipodoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateField()),
                ('descricao', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=50)),
                ('responsavel', models.CharField(max_length=100, null=True)),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro_app.eventos')),
            ],
        ),
    ]
