# Generated by Django 5.0.4 on 2024-05-01 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento_app', '0002_eventoregistro_solicitacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoregistro',
            name='descricao',
            field=models.TextField(),
        ),
    ]
